import { z } from "zod"
export const roleSchema=z.enum(["USER","ADMIN"]);export type Role=z.infer<typeof roleSchema>
export const registerSchema=z.object({email:z.string().trim().email().max(254),password:z.string().min(12).max(128).regex(/[a-z]/).regex(/[A-Z]/).regex(/[0-9]/),firstName:z.string().trim().min(2).max(80),lastName:z.string().trim().min(2).max(120)})
export const loginSchema=z.object({email:z.string().trim().email().max(254),password:z.string().min(1).max(128)})
export const profileSchema=z.object({firstName:z.string().trim().min(2).max(80),lastName:z.string().trim().min(2).max(120),phone:z.string().trim().max(25).regex(/^\+?[0-9][0-9 ()-]{5,24}$/, "Ingresa un teléfono válido con dígitos y código de país opcional.").nullable().optional(),country:z.string().trim().min(2).max(100).nullable().optional(),city:z.string().trim().max(100).nullable().optional(),headline:z.string().trim().max(180).nullable().optional(),professionalSummary:z.string().trim().max(1000).nullable().optional(),institution:z.string().trim().max(180).nullable().optional(),career:z.string().trim().max(160).nullable().optional(),graduationYear:z.number().int().min(1950).max(new Date().getUTCFullYear()+10).nullable().optional()})
export const opportunitySchema=z.object({companyName:z.string().trim().min(2).max(180),sector:z.string().trim().max(120).nullable().optional(),jobTitle:z.string().trim().min(2).max(180),sourceName:z.string().trim().max(100).nullable().optional(),sourceUrl:z.string().url().max(1000).nullable().optional().or(z.literal("")),workMode:z.enum(["REMOTE","HYBRID","ONSITE"]).nullable().optional(),location:z.string().trim().max(180).nullable().optional(),publishedOn:z.string().date().nullable().optional(),closingOn:z.string().date().nullable().optional(),notes:z.string().trim().max(2000).nullable().optional(),createApplication:z.boolean().default(false)})
export const applicationSchema=z.object({opportunityId:z.number().int().positive(),appliedOn:z.string().date().nullable().optional(),nextAction:z.string().trim().max(250).nullable().optional(),nextActionAtUtc:z.string().datetime().nullable().optional()})
export const statusChangeSchema=z.object({newStatusCode:z.enum(["REGISTERED","SENT","PRESELECTED","INTERVIEW","ASSESSMENT","OFFER","HIRED","REJECTED","WITHDRAWN"]),comment:z.string().trim().max(1000).nullable().optional()})
export const adminUserStatusSchema=z.object({isActive:z.boolean()})
export type RegisterInput=z.infer<typeof registerSchema>;export type LoginInput=z.infer<typeof loginSchema>;export type ProfileInput=z.infer<typeof profileSchema>;export type OpportunityInput=z.infer<typeof opportunitySchema>;export type ApplicationInput=z.infer<typeof applicationSchema>;export type StatusChangeInput=z.infer<typeof statusChangeSchema>
export type AuthUser={userId:string;email:string;firstName:string;lastName:string;roles:Role[]}
